name: Sync to Gitee after gh-pages build

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码，确保获取所有分支和历史
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # 2. 设置 Git 配置
    - name: Set up Git user
      run: |
        git config user.name "${{ secrets.GITEE_USERNAME }}"
        git config user.email "${{ secrets.GITEE_EMAIL }}"

    # 3. 同步到 Gitee
    - name: Sync branches to Gitee
      env:
        GITEE_REPO: jiajunlin/open-course
        GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
      run: |
        set -e
        git remote add gitee https://${{ secrets.GITEE_USERNAME }}:$GITEE_TOKEN@gitee.com/$GITEE_REPO.git
        git push gitee main:main
        git push gitee gh-pages:gh-pages --force

    # 4. 触发 Gitee Pages 重建
    - name: Trigger Gitee Pages Rebuild
      env:
        GITEE_REPO: jiajunlin/open-course
        GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
      run: |
        curl -X POST https://gitee.com/api/v5/repos/${{ secrets.GITEE_USERNAME }}/$GITEE_REPO/pages/builds \
              -H 'Content-Type: application/json;charset=UTF-8' \
              -d '{"access_token": "$GITEE_TOKEN"}'
