name: Sync to Gitee

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with full history
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Push to Gitee
      env:
        GITEE_REPO: jiajunlin/open-course
        GITEE_USERNAME: ${{ secrets.GITEE_USERNAME }}
        GITEE_EMAIL: ${{ secrets.GITEE_EMAIL }}
        GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
      run: |
        git config user.name "$GITEE_USERNAME"
        git config user.email "$GITEE_EMAIL"
        git remote add gitee https://$GITEE_USERNAME:$GITEE_TOKEN@gitee.com/$GITEE_REPO.git
        git push gitee main
        git push gitee gh-pages
